# -*- coding: utf-8 -*-
"""knn_classfi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVWAXQEb05Wqjcm11USy0a9lJTCS_Ra-
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd

df=pd.read_csv('train.csv')
df.head(5)

df['Sex1']=np.where(df['Sex']=='male',0,1)
df.head(5)

df['Embarked1']=np.where(df['Embarked']=='S',0,np.where(df['Embarked']=='C',1,2))
df.head(5)

df=df[['Survived','Pclass','Sex1','Age','SibSp','Parch','Fare','Embarked1']].dropna(axis=0,how='any')

df.head(5)

X=df[['Pclass','Sex1','Age','SibSp','Parch','Fare','Embarked1']].values
Y=df['Survived'].values

X[0:5]

Y[0:5]

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=.3)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier()
knn.fit(xtrain,ytrain)

ypred=knn.predict(xtest)

knn.n_neighbors

from sklearn.metrics import confusion_matrix,accuracy_score

confusion_matrix(ytest,ypred)

accuracy_score(ytest,ypred)